get_filename_component(CHIBIOS_VARIOUS_DIR
    ${CMAKE_CURRENT_LIST_FILE} DIRECTORY)

set(CHIBIOS_VARIOUS_SRC
    ${CHIBIOS_VARIOUS_DIR}/evtimer.c
    ${CHIBIOS_VARIOUS_DIR}/shell.c
)

set(CHIBIOS_VARIOUS_INCLUDE_DIR ${CHIBIOS_VARIOUS_DIR})
